//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublishesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Издания
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Издания()
        {
            this.Подписки = new HashSet<Подписки>();
        }
    
        public string Индекс { get; set; }
        public string Названия { get; set; }
        public string Тип_издания { get; set; }
        public int Количество_издания { get; set; }
        public string Количество
        {
            get
            {
                if (this.Количество_издания > 0)
                    return this.Количество_издания.ToString();
                else
                    return "нет в наличии";
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Подписки> Подписки { get; set; }
    }
}
